[package]
name = "fluent-codes-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusqlite = { version = "0.29", features = ["bundled"] }
rust-embed = "6.8"
rand = "0.8"